lista=[]
lista.append({'producto' : 'manzano','kcal' : '52','rendimiento' : '7000','maxMes' : '15','nu' : '800','poda' : '1.84'})
lista.append({'producto' : 'naranjo','kcal' : '47','rendimiento' : '2980','maxMes' : '15','nu' : '400','poda' : '2'})
lista.append({'producto' : 'higo','kcal' : '75','rendimiento' : '650','maxMes' : '4.5','nu' : '200'})
lista.append({'producto' : 'chirimoya','kcal' : '75','rendimiento' : '600','maxMes' : '6','nu' : '150'})
lista.append({'producto' : 'ortiga','kcal' : '309','rendimiento' : '600','maxMes' : '1'})
lista.append({'producto' : 'tomate','kcal' : '18','rendimiento' : '2500','maxMes' : '15'})
lista.append({'producto' : 'maiz','kcal' : '111','rendimiento' : '1200','maxMes' : '18'})
lista.append({'producto' : 'haba','kcal' : '314','rendimiento' : '400','maxMes' : '3'})
lista.append({'producto' : 'tupinambo','kcal' : '77','rendimiento' : '33000','maxMes' : '7'})
lista.append({'producto' : 'puerro','kcal' : '61','rendimiento' : '1200','maxMes' : '6'})
lista.append({'producto' : 'cebolla','kcal' : '40','rendimiento' : '1300','maxMes' : '6'})
lista.append({'producto' : 'marihuana', 'kcal' : '0','rendimiento' : '500','maxMes' : '0.5'})
lista.append({'producto' : 'romero','kcal': '200', 'rendimiento' : '200','maxMes' : '0.06'})
lista.append({'producto' : 'ruda', 'kcal' : '82','rendimiento' : '1400','maxMes' : '0.03'})
lista.append({'producto' : 'chirivia','kcal' : '75','rendimiento' : '2500','maxMes' : '6'})
lista.append({'producto' : 'ajo','kcal' : '149','rendimiento' : '250','maxMes' : '1'})
lista.append({'producto' : 'ñora','kcal' : '80','rendimiento' : '2100','maxMes' : '7'})
lista.append({'producto' : 'oliva','kcal' : '115','rendimiento' : '2000','maxMes' : '9','nu' : '100','poda' : '0.15'})
lista.append({'producto' : 'zanahoria','kcal' : '40','rendimiento' : '1700','maxMes' : '3'})
lista.append({'producto' : 'col','kcal' : '25','rendimiento' : '3500','maxMes' : '3'})
lista.append({'producto' : 'boniato','kcal' : '86','rendimiento' : '3000','maxMes' : '15'})
lista.append({'producto' : 'pepino','kcal' : '11','rendimiento' : '1100','maxMes' : '8'})
lista.append({'producto' : 'pimientoRojo','kcal' : '26','rendimiento' : '2000','maxMes' : '9'})
lista.append({'producto' : 'remolacha','kcal' : '43','rendimiento' : '4160','maxMes' : '3'})
lista.append({'producto' : 'brocoli','kcal' : '28','rendimiento' : '1500','maxMes' : '2'})
lista.append({'producto' : 'calabaza','kcal' : '45','rendimiento' : '1700','maxMes' : '15'})
lista.append({'producto' : 'rabano','kcal' : '16','rendimiento' : '1700','maxMes' : '1'})
lista.append({'producto' : 'nabo','kcal' : '28','rendimiento' : '1200','maxMes' : '1'})
lista.append({'producto' : 'patata','kcal' : '77','rendimiento' : '2500','maxMes' : '10'})
lista.append({'producto' : 'huevo','kcal' : '76', 'rendimiento' : '2650','maxMes' : '4.5'})
lista.append({'producto' : 'cilandro','kcal' : '20','rendimiento' : '1400','maxMes' : '1'})
lista.append({'producto' : 'menta', 'kcal' : '99','rendimiento' : '700','maxMes' : '0.03'})
lista.append({'producto' : 'uvaTinta','kcal' : '70','rendimiento' : '400','maxMes' : '3'})
lista.append({'producto' : 'yuca dulce','kcal' : '130','rendimiento' : '1000','maxMes' : '2'})
lista.append({'producto' : 'AlgarroboNegro','kcal' : '222','rendimiento' : '200','maxMes' : '2'})
lista.append({'producto' : 'Falsa Banana','kcal' : '330','rendimiento' : '10000','maxMes' : '10'})
lista.append({'producto' : 'Ñame','kcal' : '118','rendimiento' : '850','maxMes' : '7'})
lista.append({'producto' : 'Salsifi','kcal' : '82','rendimiento' : '1700','maxMes' : '7'})
lista.append({'producto' : 'Albahaca','kcal' : '22','rendimiento' : '1800','maxMes' : '2'})
lista.append({'producto' : 'Moringa','kcal' : '50','rendimiento' : '15000','maxMes' : '10'})
lista.append({'producto' : 'Curcuma','kcal' : '300','rendimiento' : '1500','maxMes' : '10'})
lista.append({'producto' : 'Kiwi','kcal' : '61','rendimiento' : '3000','maxMes' : '3'})
lista.append({'producto' : 'TomateCherrie','kcal' : '18','rendimiento' : '4200','maxMes' : '15'})
lista.append({'producto' : 'Oca','kcal' : '61','rendimiento' : '1200','maxMes' : '10'})
lista.append({'producto' : 'Chufa','kcal' : '409','rendimiento' : '1200','maxMes' : '5'})
lista.append({'producto' : 'Membrillo','kcal' : '57','rendimiento' : '6660','maxMes' : '15','nu' : '450'})
lista.append({'producto' : 'Pomelo','kcal' : '42','rendimiento' : '7000','maxMes' : '15','nu' : '500','poda' : '2'})
lista.append({'producto' : 'Nispero','kcal' : '40','rendimiento' : '2000','maxMes' : '3','nu' : '400'})
lista.append({'producto' : 'Avellana','kcal' : '628','rendimiento' : '250','maxMes' : '1','nu' : '475'})
lista.append({'producto' : 'Nuez','kcal' : '607','rendimiento' : '150','maxMes' : '1','nu' : '450'})
lista.append({'producto' : 'Platano','kcal' : '89','rendimiento' : '3000','maxMes' : '3','nu' : '2000'})
lista.append({'producto' : 'Pistacho','kcal' : '562','rendimiento' : '500','maxMes' : '2','nu' : '275'})
lista.append({'producto' : 'CañaAzucar','kcal' : '20','rendimiento' : '7000','maxMes' : '25'})
lista.append({'producto' : 'Fresa','kcal' : '35','rendimiento' : '1000','maxMes' : '5'})
lista.append({'producto' : 'Garbanzo','kcal' : '364','rendimiento' : '280','maxMes' : '5'})
lista.append({'producto' : 'Lenteja','kcal' : '352','rendimiento' : '80','maxMes' : '2'})
lista.append({'producto' : 'Alubia','kcal' : '349','rendimiento' : '250','maxMes' : '5'})
lista.append({'producto' : 'Arroz','kcal' : '359','rendimiento' : '400','maxMes' : '5'})
lista.append({'producto' : 'Berza','kcal' : '32','rendimiento' : '1500','maxMes' : '5'})
lista.append({'producto' : 'Espinaca','kcal' : '23','rendimiento' : '1500','maxMes' : '5'})
lista.append({'producto' : 'Escarola','kcal' : '17','rendimiento' : '1666','maxMes' : '5'})